name: Automated Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./automated-testing

      - name: Build TypeScript
        run: npx tsc
        working-directory: ./automated-testing

      - name: Run tests
        run: npm test
        working-directory: ./automated-testing